sudo: false
language: bash
git:
  depth: 1
  submodules: true
os: linux
dist: xenial
addons:
  snaps:
    - name: hugo
      channel: extended/stable
script:
  - hugo
  - touch public/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  target_branch: master
  github_token: $GITHUB_TOKEN
  on:
    branch: source
notifications:
  email:
    on_success: never
    on_failure: always
