[book]
authors = ["Ilya Siganov"]
multilingual = false
src = "src"
title = "FCS Programming"

[output.html]
mathjax-support = true

[output.linkcheck]
# Should we check links on the internet? Enabling this option adds a
# non-negligible performance impact
follow-web-links = false

# Are we allowed to link to files outside of the book's root directory? This
# may help prevent linking to sensitive files (e.g. "../../../../etc/shadow")
traverse-parent-directories = false